# Generated by Django 4.2.11 on 2024-03-13 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentLastName', models.CharField(max_length=20)),
                ('studentFirstName', models.CharField(max_length=20)),
                ('studentGender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('studentAge', models.PositiveIntegerField()),
                ('studentContactNumber', models.CharField(default='', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must contain only digits.', regex='^[0-9]+$')], verbose_name='Contact Number')),
                ('emergencyContactName', models.CharField(max_length=20)),
                ('emergencyContactNumber', models.CharField(default='', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must contain only digits.', regex='^[0-9]+$')], verbose_name='Emergency Contact Number')),
            ],
        ),
    ]
