# Generated by Django 4.2.11 on 2024-03-14 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_students_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentAge',
        ),
        migrations.AddField(
            model_name='student',
            name='studentDOB',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
