# Generated by Django 4.2.11 on 2024-03-24 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_studentage_student_studentdob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='emergencyContactName',
            field=models.CharField(max_length=20, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentDOB',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentFirstName',
            field=models.CharField(max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentGender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentLastName',
            field=models.CharField(max_length=20, verbose_name='Last Name'),
        ),
    ]
