# Generated by Django 4.2.11 on 2025-04-04 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_emergencycontactname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonPlan', models.CharField(choices=[('8', '8 Lessons'), ('4', '4 Lessons'), ('1', '1 Lesson')], max_length=1, verbose_name='Lesson Plan')),
                ('remainingLessons', models.IntegerField(default=0)),
                ('planOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
