# Generated by Django 4.2.11 on 2024-03-25 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_course_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_end_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_start_time',
        ),
        migrations.AddField(
            model_name='course',
            name='course_end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='course',
            name='course_start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
