# Generated by Django 4.2.11 on 2024-04-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_session_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='first_session_pointer',
            field=models.IntegerField(null=True),
        ),
    ]
