# Generated by Django 4.2.11 on 2024-07-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_first_session_pointer'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='session_number',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='first_session_pointer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='session_number',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
