# Generated by Django 4.2.11 on 2024-07-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_enrollment_session_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='first_session_pointer',
        ),
        migrations.RemoveField(
            model_name='course',
            name='session_number',
        ),
    ]
