# Generated by Django 4.2.11 on 2024-07-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_first_session_pointer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payday',
            field=models.BooleanField(default=False),
        ),
    ]
