# Generated by Django 4.2.11 on 2024-07-12 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_enrollment_payday'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_time',
            field=models.TimeField(default=datetime.time(17, 19, 50, 938926)),
        ),
    ]
