# Generated by Django 4.2.11 on 2024-07-15 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_course_course_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_end',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_start',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
