# Generated by Django 4.2.11 on 2024-11-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_course_date_alter_course_course_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
    ]
