# Generated by Django 4.2.11 on 2025-03-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_enrollment_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(choices=[('Kids Parkour', 'Kids Parkour'), ('Adults Parkour', 'Adults Parkour')], max_length=20, verbose_name='Class'),
        ),
    ]
