# Generated by Django 4.2.11 on 2025-03-18 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_course_course_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regClass_title', models.CharField(choices=[('Kids Parkour', 'Kids Parkour'), ('Adults Parkour', 'Adults Parkour')], max_length=20, verbose_name='Class')),
                ('regClass_date', models.DateField(default=datetime.datetime.now)),
                ('regClass_start', models.TimeField(default=datetime.datetime.now)),
                ('regClass_end', models.TimeField(default=datetime.datetime.now)),
                ('regClass_fee', models.IntegerField(default=0)),
            ],
        ),
    ]
